error=/usr/include/errorunp.c
wrap=/home/zgf/clianxi/NetworkProgram/lib/wrapsock.c
out:
	gcc -o daytimeserv datytimesrv1.c $(wrap) $(error)
	gcc -o daytimecli daytimecli1.c $(wrap) $(error)
clean:
	rm daytimeserv daytimecli
